### ISSUE TITLE
Can you help me about a export problem? System.DllNotFoundException: steam_api assembly:<unknown assembly> type:<unknown type> member:(null)

### ISSUE THREAD

**Issue by RightFS** [chickensoft-games/GameTemplate#2]
platform: macos

My game can run in editor but cannot run after exported. I inspect the main pck and there is a libsteam_api.dylib and the bundle.
And I tried copy the dylib and/or the bundle file into xxx.app/Contents/MacOS/, the xxx.app/Contents/Frameworks and xxx.app/Contents/Resouces/, no one is the right path, mono always says no dll found. I'm crazy for this stupid problem. 

Apple's OS is garbage in low-level mechanism.

Thanks for everything.

**Comment by jolexxa** [comment]
See this: https://github.com/godotengine/godot/issues/61313#issuecomment-1135202301

**Comment by RightFS** [comment]
I traced the system calls to find what paths dose mono try open. Then I found it try `Contents/Libraries` and `Contents/lib` instead of Frameworks, so I put the dylibs into `Contents/Libraries` and it works. 

Thanks for reply, have a nice day. I'm struggling with the  load path of pck files...

**Comment by jolexxa** [comment]
@RightFS Glad you got it working :D
